---
- name: systemd daemon-reload
  become: yes
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: start rundeck
  include_tasks: "{{role_path}}/handlers/start_rundeck.yml"
  vars:
    rundeckd_state: started

- name: restart rundeck
  include_tasks: "{{role_path}}/handlers/start_rundeck.yml"
  vars:
    rundeckd_state: restarted
